"""Persona models for victim profile generation.

This module contains Pydantic models and enums for representing
victim personas used by the Persona Engine to generate believable
responses in phishing engagement conversations.
"""

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class PersonaType(str, Enum):
    """Types of victim personas that PhishGuard can roleplay.

    Each persona type has distinct characteristics that make them
    believable targets for specific types of phishing attacks.

    Attributes:
        NAIVE_RETIREE: Trusting elderly person, ideal for 419/romance scams.
        STRESSED_MANAGER: Busy professional, vulnerable to CEO fraud.
        GREEDY_INVESTOR: Risk-taker seeking high returns, target for crypto scams.
        CONFUSED_STUDENT: Less tech-savvy person, susceptible to tech support scams.
    """

    NAIVE_RETIREE = "naive_retiree"
    """Trusting elderly person with savings, ideal for advance-fee or romance scams."""

    STRESSED_MANAGER = "stressed_manager"
    """Busy professional who might rush decisions, vulnerable to business scams."""

    GREEDY_INVESTOR = "greedy_investor"
    """Risk-taker seeking high returns, target for investment and crypto scams."""

    CONFUSED_STUDENT = "confused_student"
    """Less experienced person easily intimidated by technical scams."""

    @property
    def display_name(self) -> str:
        """Return a human-readable display name for the persona type.

        Returns:
            A formatted string suitable for UI display.

        Example:
            >>> PersonaType.NAIVE_RETIREE.display_name
            'Naive Retiree'
            >>> PersonaType.STRESSED_MANAGER.display_name
            'Stressed Manager'
        """
        display_names: dict[PersonaType, str] = {
            PersonaType.NAIVE_RETIREE: "Naive Retiree",
            PersonaType.STRESSED_MANAGER: "Stressed Manager",
            PersonaType.GREEDY_INVESTOR: "Greedy Investor",
            PersonaType.CONFUSED_STUDENT: "Confused Student",
        }
        return display_names[self]


class PersonaProfile(BaseModel):
    """Complete profile for a victim persona used in conversation.

    This model encapsulates all attributes of a generated persona,
    including identity details from Faker and behavioral characteristics.

    Attributes:
        persona_type: The category of victim persona.
        name: Full name generated by Faker for consistency.
        age: Age appropriate for the persona type.
        style_description: Brief description of communication style.
        background: Short background story for the persona.

    Example:
        >>> profile = PersonaProfile(
        ...     persona_type=PersonaType.NAIVE_RETIREE,
        ...     name="Margaret Thompson",
        ...     age=72,
        ...     style_description="Trusting and polite, uses formal language",
        ...     background="Retired teacher, recently widowed"
        ... )
        >>> profile.persona_type.display_name
        'Naive Retiree'
    """

    model_config = ConfigDict(
        frozen=True,
        validate_assignment=True,
        use_enum_values=False,
    )

    persona_type: PersonaType = Field(
        ...,
        description="The category of victim persona being roleplayed.",
    )
    name: str = Field(
        ...,
        description="Full name for the persona, generated by Faker.",
        min_length=1,
        max_length=100,
        json_schema_extra={
            "examples": ["Margaret Thompson", "David Chen", "Robert Williams"],
        },
    )
    age: int = Field(
        ...,
        description="Age of the persona, appropriate for the persona type.",
        ge=18,
        le=95,
        json_schema_extra={
            "examples": [72, 45, 35, 22],
        },
    )
    style_description: str = Field(
        ...,
        description="Brief description of communication style and mannerisms.",
        min_length=1,
        json_schema_extra={
            "examples": [
                "Trusting and polite, easily confused by technology",
                "Impatient and busy, prefers brief messages",
            ],
        },
    )
    background: str = Field(
        ...,
        description="Short background story providing context for the persona.",
        min_length=1,
        json_schema_extra={
            "examples": [
                "Retired teacher, recently widowed, lives alone",
                "Marketing director at mid-size company, managing multiple projects",
            ],
        },
    )

    @property
    def summary(self) -> str:
        """Generate a one-line summary of the persona.

        Returns:
            A brief summary string suitable for display.

        Example:
            >>> profile.summary
            'Margaret Thompson, 72 - Naive Retiree'
        """
        return f"{self.name}, {self.age} - {self.persona_type.display_name}"
