"""Conversation models for PhishGuard chat interactions.

This module contains Pydantic models for representing conversation messages
and response generation results in the PhishGuard conversation loop.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field

from phishguard.models.thinking import AgentThinking


class MessageSender(str, Enum):
    """Identifies the sender of a conversation message.

    Attributes:
        BOT: Message from the PhishGuard bot (victim persona).
        SCAMMER: Message from the scammer being engaged.
    """

    BOT = "bot"
    """Message generated by PhishGuard in the victim persona."""

    SCAMMER = "scammer"
    """Message from the scammer (pasted by user)."""


class ConversationMessage(BaseModel):
    """A single message in the conversation history.

    Represents either a bot-generated response or a scammer message
    pasted by the user. Messages are timestamped for timeline tracking.

    Attributes:
        sender: Who sent the message (bot or scammer).
        content: The text content of the message.
        timestamp: When the message was created/received.
        turn_number: The conversation turn this message belongs to.

    Example:
        >>> msg = ConversationMessage(
        ...     sender=MessageSender.BOT,
        ...     content="Oh my, this sounds wonderful!",
        ...     turn_number=1
        ... )
        >>> msg.is_bot_message
        True
    """

    model_config = ConfigDict(
        frozen=True,
        validate_assignment=True,
        use_enum_values=False,
    )

    sender: MessageSender = Field(
        ...,
        description="Identifies who sent this message.",
    )
    content: str = Field(
        ...,
        description="The text content of the message.",
        min_length=1,
    )
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(UTC),
        description="When the message was created.",
    )
    turn_number: int = Field(
        ...,
        description="The conversation turn number (1-based).",
        ge=1,
    )

    @property
    def is_bot_message(self) -> bool:
        """Check if this message was sent by the bot.

        Returns:
            True if the message is from the bot, False otherwise.
        """
        return self.sender == MessageSender.BOT

    @property
    def is_scammer_message(self) -> bool:
        """Check if this message was sent by the scammer.

        Returns:
            True if the message is from the scammer, False otherwise.
        """
        return self.sender == MessageSender.SCAMMER


class ResponseGenerationResult(BaseModel):
    """Result of generating a response through the Conversation Agent.

    Contains the generated response content along with metadata about
    the generation process, including timing and safety validation status.

    Attributes:
        content: The generated response text.
        generation_time_ms: Time taken to generate the response in milliseconds.
        safety_validated: Whether the response passed safety validation.
        regeneration_count: Number of times response was regenerated due to safety.
        used_fallback_model: Whether the fallback LLM model was used.
        thinking: Agent's strategic thinking for this response.

    Example:
        >>> result = ResponseGenerationResult(
        ...     content="Oh dear, I'm very interested!",
        ...     generation_time_ms=2500,
        ...     safety_validated=True,
        ...     regeneration_count=0,
        ...     used_fallback_model=False
        ... )
        >>> result.generation_time_seconds
        2.5
    """

    model_config = ConfigDict(
        frozen=True,
        validate_assignment=True,
    )

    content: str = Field(
        ...,
        description="The generated response text.",
        min_length=1,
    )
    generation_time_ms: int = Field(
        ...,
        description="Time to generate the response in milliseconds.",
        ge=0,
    )
    safety_validated: bool = Field(
        default=True,
        description="Whether the response passed safety validation.",
    )
    regeneration_count: int = Field(
        default=0,
        description="Number of regeneration attempts due to safety violations.",
        ge=0,
    )
    used_fallback_model: bool = Field(
        default=False,
        description="Whether the fallback LLM model was used.",
    )
    thinking: AgentThinking | None = Field(
        default=None,
        description="Agent's strategic thinking for this response, if available.",
    )

    @property
    def has_thinking(self) -> bool:
        """Check if thinking data is available for this response.

        Returns:
            True if thinking data is present, False otherwise.
        """
        return self.thinking is not None

    @property
    def generation_time_seconds(self) -> float:
        """Get generation time in seconds.

        Returns:
            Generation time as a float in seconds.
        """
        return self.generation_time_ms / 1000.0

    @property
    def was_regenerated(self) -> bool:
        """Check if the response required regeneration.

        Returns:
            True if the response was regenerated at least once.
        """
        return self.regeneration_count > 0
